# Keras MNIST Example

### Import MNIST data from TensorFlow

In [3]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot = True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


### Import Keras 

In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation

Using TensorFlow backend.


### Define model structure

In [39]:
model = Sequential()
model.add(Dense(32, input_shape=(784,)))
model.add(Activation('relu'))
model.add(Dense(10))
model.add(Activation('softmax'))

In [40]:
model.compile(optimizer = 'rmsprop',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])

### Train model

In [14]:
from datetime import datetime

In [44]:
print("training start:", str(datetime.now()))
model.fit(mnist.train.images, 
          mnist.train.labels, 
          epochs = 10, 
          batch_size = 32,
          validation_data = (mnist.validation.images, mnist.validation.labels))
print("training end:", str(datetime.now()))

training start: 2018-01-09 20:07:18.226366
Train on 55000 samples, validate on 5000 samples
Epoch 1/10
55000/55000 [==============================] - 2s 34us/step - loss: 0.0061 - acc: 0.9987 - val_loss: 0.2671 - val_acc: 0.9614
Epoch 2/10
55000/55000 [==============================] - 2s 33us/step - loss: 0.0067 - acc: 0.9985 - val_loss: 0.2609 - val_acc: 0.9628
Epoch 3/10
55000/55000 [==============================] - 2s 33us/step - loss: 0.0069 - acc: 0.9984 - val_loss: 0.2616 - val_acc: 0.9628
Epoch 4/10
55000/55000 [==============================] - 2s 33us/step - loss: 0.0068 - acc: 0.9982 - val_loss: 0.2754 - val_acc: 0.9616
Epoch 5/10
55000/55000 [==============================] - 2s 33us/step - loss: 0.0070 - acc: 0.9983 - val_loss: 0.2795 - val_acc: 0.9620
Epoch 6/10
55000/55000 [==============================] - 2s 34us/step - loss: 0.0070 - acc: 0.9983 - val_loss: 0.2679 - val_acc: 0.9626
Epoch 7/10
55000/55000 [==============================] - 2s 33us/step - loss: 0.0071 

### Get model weights

In [45]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 32)                25120     
_________________________________________________________________
activation_3 (Activation)    (None, 32)                0         
_________________________________________________________________
dense_5 (Dense)              (None, 10)                330       
_________________________________________________________________
activation_4 (Activation)    (None, 10)                0         
Total params: 25,450
Trainable params: 25,450
Non-trainable params: 0
_________________________________________________________________


In [53]:
model.get_layer("dense_5").get_weights()[0].shape

(32, 10)

In [54]:
model.get_layer("dense_5").get_weights()[1].shape

(10,)

In [56]:
model.get_layer("dense_4").get_weights()[0].shape

(784, 32)

In [57]:
model.get_layer("dense_4").get_weights()[1].shape

(32,)

### Mulitply weights by inputs

In [60]:
np.dot(mnist.train.images, model.get_layer("dense_4").get_weights()[0]).shape

(55000, 32)

In [68]:
single_row = mnist.train.images[0,]
single_row.shape

(784,)

In [69]:
x1 = np.arange(12.0).reshape((4, 3))
print("x1:", x1, x1.shape)
x2 = np.arange(3.0)
print("x2:", x2, x2.shape)
np.multiply(x1, x2)

x1: [[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]] (4, 3)
x2: [0. 1. 2.] (3,)


array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.],
       [ 0., 10., 22.]])

In [73]:
layer1_coef_x_input = np.multiply(np.transpose(model.get_layer("dense_4").get_weights()[0]),
                                  single_row)
layer1_coef_x_input.shape

(32, 784)

In [80]:
model.layers[1].output.get_shape()

TensorShape([Dimension(None), Dimension(32)])